mysql:
  user: root
  password: ${mysql_password}
  host: 127.0.0.1
  port: 3306
  database: ganxue_server
redis:
  addr: 172.21.126.176:6379
  password: ""
  db: 0
email:
  from: ""
  host: smtp.163.com
  port: 465
  username: ""
  password: ""